services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    # build: ./backend
    # container_name: backend
    # restart: always
    # depends_on:
    #   - mongo
    # environment:
    #   - MONGO_URL=mongodb://mongo:27017/dd_db
    image: parthghl00/backend:latest
    ports:
      - "8080:8080"

  frontend:
    # build: ./frontend
    # container_name: frontend
    # restart: always
    # depends_on:
    #   - backend
    image: parthghl00/frontend:latest
    ports:
      - "80:80"

volumes:
  mongo-data: